title: MotifMinimalism
description: Minimal, code-first UiPath Maestro explorations of core runtime constructs, capturing the essence of execution semantics in standalone solutions.
include: ['_pages']
markdown: kramdown
github_url: https://github.com/rpapub/MotifMinimalism
brand_icon_fontawesome_pro: folder-music
source: .
layouts_dir: ./webpage/_layouts
includes_dir: ./webpage/_includes
collections_dir: ./webpage/collections
data_dir: ./webpage/_data
theme: null
baseurl: /MotifMinimalism

collections:
  pages:
    output: true
    permalink: /:path
  schemas:
    output: true
    permalink: /schemas/:path
  solution-examples:
    output: true
    permalink: /minimals/:slug/
  dummy:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: webawesome

exclude:
  - script/

feedback_url:
  general: https://github.com/rpapub/MotifMinimalism/issues/
  docs: https://github.com/rpapub/MotifMinimalism/issues/new?template=documentation-improvement.yml
discussion_url:
  general: https://github.com/orgs/rpapub/discussions/categories/motifminimalism-general

webmaster:
  - name: Christian Prior-Mamulyan
    github: cprima
    url: cprima.net
    email: cprior@gmail.com
    job_title: IT Enthusiast
    same_as:
      - https://github.com/cprima
      - https://www.linkedin.com/in/cprima/
    image: https://avatars.githubusercontent.com/u/943871
    affiliation: RPA Publishing
    description: Listening to biz, talking with IT. Thinking ahead.
